import type {DriveCycle} from '../../src/core/drive-cycle';
import type {SignalFits} from '../../src/core/signals';
import type {VehicleTraits} from '../../src/core/traits';
import type {VehicleProfile} from '../../src/core/types';
import type {SimulatorProvenance} from '../../src/simulators/types';

// Renders the generated TypeScript modules. Layout is left to the formatter
// (`npm run import-vehicle` runs Biome over the output).

const BANNER = [
    '// GENERATED by tools/import-vehicle from wire logs of a real vehicle — do not edit.',
    '// Re-run `npm run import-vehicle` instead (see docs/ADDING-A-VEHICLE.md).',
    '',
].join('\n');

const hex = (value: number, width = 2): string => `0x${value.toString(16).padStart(width, '0')}`;
const hexList = (values: readonly number[], width = 2): string => `[${values.map((value) => hex(value, width)).join(', ')}]`;
const quoted = (value: string): string => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function renderEcus(profile: VehicleProfile): string {
    const ecus = (profile.additionalEcus ?? []).map((ecu) =>
        [
            '{',
            `id: ${quoted(ecu.id)},`,
            ecu.name ? `name: ${quoted(ecu.name)},` : '',
            `pids: ${hexList(ecu.pids)},`,
            ecu.readiness ? `readiness: ${hexList(ecu.readiness)},` : '',
            ecu.calibrationId ? `calibrationId: ${quoted(ecu.calibrationId)},` : '',
            ecu.cvn ? `cvn: ${quoted(ecu.cvn)},` : '',
            ecu.dtcReply ? `dtcReply: ${quoted(ecu.dtcReply)},` : '',
            '},',
        ]
            .filter((line) => line !== '')
            .join('\n'),
    );
    return ecus.length > 0 ? `additionalEcus: [\n${ecus.join('\n')}\n],` : '';
}

export function renderProfileModule(profile: VehicleProfile, provenance: SimulatorProvenance): string {
    const tests = profile.monitorTests.map(
        (test) =>
            `{mid: ${hex(test.mid)}, tid: ${hex(test.tid)}, uasId: ${hex(test.uasId)}, value: ${hex(test.value, 4)}, min: ${hex(test.min, 4)}, max: ${hex(test.max, 4)}},`,
    );
    return [
        BANNER,
        "import type {VehicleProfile} from '../../core/types';",
        "import type {SimulatorProvenance} from '../../simulators/types';",
        '',
        'export const PROFILE: VehicleProfile = {',
        `name: ${quoted(profile.name)},`,
        '// Manufacturer, model and year as recorded; the serial is synthetic.',
        `vin: ${quoted(profile.vin)},`,
        `calibrationId: ${quoted(profile.calibrationId)},`,
        `cvn: ${quoted(profile.cvn)},`,
        `ecuName: ${quoted(profile.ecuName)},`,
        `ignition: ${quoted(profile.ignition)},`,
        `pids: ${hexList(profile.pids)},`,
        `readinessSinceClear: ${hexList(profile.readinessSinceClear)},`,
        `readinessThisDriveCycle: ${hexList(profile.readinessThisDriveCycle)},`,
        `performanceCounters: [${profile.performanceCounters.join(', ')}],`,
        `monitorTests: [\n${tests.join('\n')}\n],`,
        profile.protocol ? `protocol: ${quoted(profile.protocol)},` : '',
        renderEcus(profile),
        `supportsPermanentDtcs: ${profile.supportsPermanentDtcs !== false},`,
        profile.framePadding === undefined ? '' : `framePadding: ${hex(profile.framePadding)},`,
        '};',
        '',
        'export const PROVENANCE: SimulatorProvenance = {',
        `sessions: ${provenance.sessions},`,
        `from: ${quoted(provenance.from)},`,
        `to: ${quoted(provenance.to)},`,
        `importerVersion: ${quoted(provenance.importerVersion)},`,
        '};',
        '',
    ]
        .filter((line, index, lines) => line !== '' || lines[index - 1] !== '')
        .join('\n');
}

export function renderDrivingModule(cycle: DriveCycle, traits: Partial<VehicleTraits>, signals: SignalFits = {}): string {
    const channel = (name: keyof DriveCycle): string => {
        const samples = cycle[name];
        return Array.isArray(samples) ? `${name}: [${samples.join(', ')}],` : '';
    };
    return [
        BANNER,
        "import type {DriveCycle} from '../../core/drive-cycle';",
        "import type {SignalFits} from '../../core/signals';",
        "import type {VehicleTraits} from '../../core/traits';",
        '',
        'export const TRAITS: Partial<VehicleTraits> = {',
        ...Object.entries(traits).map(([key, value]) => `${key}: ${value},`),
        '};',
        '',
        '// How each PID followed load, rpm and speed in the recordings (least squares; constants where unrelated).',
        'export const SIGNALS: SignalFits = {',
        ...Object.entries(signals).map(
            ([pid, fit]) =>
                `${hex(Number(pid))}: {base: ${fit.base}, perLoadPct: ${fit.perLoadPct}, perKrpm: ${fit.perKrpm}, perKmh: ${fit.perKmh}, min: ${fit.min}, max: ${fit.max}, noise: ${fit.noise}},`,
        ),
        '};',
        '',
        `// ${cycle.speedKmh.length} samples, ${cycle.stepSeconds} s apart, starting and ending at standstill.`,
        'export const CYCLE: DriveCycle = {',
        `stepSeconds: ${cycle.stepSeconds},`,
        channel('speedKmh'),
        channel('rpm'),
        channel('throttlePct'),
        channel('engineLoadPct'),
        channel('fuelRateLph'),
        '};',
        '',
    ].join('\n');
}
